### ISSUE TITLE
Scheduled weekly activitities.

### ISSUE THREAD

**Issue by mkrugr** [jasperweyne/helpless-kiwi#274] opened 2022-04-13 18:43 UTC
This is a request from Viakunst admin. It is pretty straight-forward, but it remains to be seen if this will be implemented.

**Comment by A-Daneel** [comment] 2022-04-14 18:38
How does this differ from issue #129?

**Comment by jasperweyne** [comment] 2024-11-02 14:26
Closing as a duplicate of #129

**Closed by jasperweyne** 2024-11-02 14:26 UTC
